#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025 Yuna Furuhata
# SPDX-License-Identifier: BSD-3-Clause
import sys
   
try:
    data = sys.stdin.read().strip()
    if not data:    
        raise ValueError
    
    items = data.split()
    num = float(items[0])

    weather = None
    if len(items) >= 2:
        weather = items[1]
    
    if num >= 25:
        advice = "夏日。半袖などの涼しい服装"

    elif 20 <= num < 25:
        advice = "薄めのジャケット"

    elif 15 <= num < 20 :
        advice = "薄手のセーターやカーディガン、秋冬コート"
    elif 10<= num < 15:
        advice = "厚手のセーターやスウェット"
    elif 5 <=  num < 10:
        advice = "ダウンやウールのコート+手袋、マフラー"
    elif num <5:
        advice = "厚めのダウンやコート、中にヒートテックなどの防寒必須"
    print("服装:", advice)

    if weather:
        
        if weather in ["雨","あめ"]:
             print("傘と撥水加工のある上着がおすすめ")
        elif weather in ["雪", "ゆき"]:
             print("ブーツや手袋、カイロがあるといい")
        elif weather in ["曇り","くもり"]:
             print("日差しがなく少し肌寒いかも")
        elif weather in ["晴れ", "はれ"]:
             print("日中は日差しが熱くなるかも")
        

        
except ValueError:
    print("エラー:数値を入力してください", file=sys.stderr)
    sys.exit(1)
    

